name: release

on:
    push:
        branches:
            - '**'
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v3
                with:
                    # list of Docker images to use as base name for tags
                    images: |
                        ghcr.io/deep-entertainment/act-godot
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Log in to registry
                run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
